#!/usr/bin/env bash

source "${ONE_PIPELINE_PATH}/internal/tools/logging"

list_repos | while IFS= read -r repo ; do
  url="$(load_repo "$repo" url)"
  name=$(echo "$url" | cut -f5 -d/)
  path="$(load_repo "$repo" path)"

  if [ -f "$WORKSPACE"/"$path"/sonar-project.properties ]; then
    debug "Using user provided 'sonar-project.properties' file"
  else
    SONAR_PROJECT_KEY=$name"-compliance-check"
    mkdir -p "$WORKSPACE"/"$path"
    touch "$WORKSPACE"/"$path"/sonar-project.properties

    cat << EOF > "$WORKSPACE"/"$path"/sonar-project.properties
sonar.projectKey=$SONAR_PROJECT_KEY
sonar.host.url=$SONAR_HOST_URL
sonar.sources=.
sonar.login=$SONAR_USER
sonar.password=$SONAR_PASS
EOF

  fi

done
